### ISSUE TITLE
Microsoft.Sql/servers not supporting changing AAD admin with templating

### ISSUE THREAD

**Issue by jikuja** [Azure/bicep-types-az#2320]
**Bicep version**
Bicep CLI version 0.4.1008 (223b8d227a)

**Describe the bug**
Re-deployment Microsoft.Sql/servers [2020-11-01-preview and 2021-05-01-preview and probably others] does not change AD admin property(properties.administrators).

**To Reproduce**
Deploy template once:
```bicep
targetScope = 'resourceGroup'

param location string

param environmentName string
param project string
param tags object

param sqlAdministratorLogin string
@secure()
param sqlAdministratorLoginPassword string
param administrators object

resource SqlServer 'Microsoft.Sql/servers@2021-05-01-preview' = {
  name: '${project}-${environmentName}-sqlserver'
  location: location
  tags: tags
  properties: {
    administratorLogin: sqlAdministratorLogin
    administratorLoginPassword: sqlAdministratorLoginPassword
    version: '12.0'
    administrators: administrators
  }
}
```
params:
```json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
      "administrators": {
        "value": {
          "administratorType": "ActiveDirectory",
          "azureADOnlyAuthentication": false,
          "principalType": "Group",
          "tenantId": "0a8edbb9-xxxx-xxxx-xxxx-2cd241f8236f",
          "sid": "5bc4b275-xxxx-xxxx-xxxx-2fb5b5ff5fe1",
          "login": "SQL Admin2"
        }
      }
    }
  }
```
----
Change sid and login to other AAD group and run What-If analysis. Results:
```
The deployment will update the following scope:

Scope: /subscriptions/8a4fb900-xxxx-xxxx-xxxx-7faf38f07f51/resourceGroups/sqltest-rg

  = Microsoft.Sql/servers/xyz-test-sqlserver [2021-05-01-preview]
    x properties.version: "12.0"

  * Microsoft.Sql/servers/xyz-test-sqlserver/databases/master
  * Microsoft.Sql/servers/xyz-test-sqlserver/databases/my-sql

Resource changes: 1 no change, 2 to ignore.
```
* No changes visible here.
----
Re-deploy template with new parameters and check AAD admin value on the portal:
* Old AAD admin is still being used

**Additional context**

Running API request changes AAD admin value:
```
Invoke-AzRestMethod -Path "/subscriptions/8a4fb900-xxxx-xxxx-xxxx-7faf38f07f51/resourceGroups/sqltest-rg/providers/Microsoft.Sql/servers/xyz-test-sqlserver/administrators/activeDirectory?api-version=2021-05-01-preview" -Method PUT -Payload $payload

Headers    : {[Cache-Control, System.String[]], [Pragma, System.String[]], [Location, System.String[]], [Retry-After, System.String[]]…}
Version    : 1.1
StatusCode : 202
Method     : PUT
Content    : {"operation":"UpdateActiveDirectoryAdministrator","startTime":"2021-10-26T08:22:02.33Z"}
```

**Comment by juho-turunen-tampuuri** [comment]
> To be completely honest, I haven't deleted our SQL server to test creation of a new SQL resource yet. But updating works 😛

As it says in the article you referenced

> If you attempt to reference a resource that doesn't exist, you get the **NotFound** error and your deployment fails. Check the name and scope of the resource you're trying to reference.

So trying to check if a resource exists in bicep only will not work.

In our case we use a script in the pipeline to check if the server exists and pass that information to the bicep deployment.

Using a DeploymentScript resource in bicep to do the checking might work also.

**Comment by damu9618** [comment]
I have the following template
    "resources": [
        {
            "type": "Microsoft.Sql/servers",
            "name": "[parameters('serverName')]",
            "apiVersion": "2022-05-01-preview",
            "location": "[resourceGroup().location]",
            "tags": "[union(parameters('resourceTags'), json('{ \"IntendedUse\": \"Hosting the application database\" }'))]",
            "properties": {
                "administrators": {
                    "login": "[parameters('databaseServerActiveDirectoryAdministrator')]",
                    "sid": "[parameters('databaseServerActiveDirectoryAdministratorSid')]",
                    "tenantId": "[subscription().tenantId]",
                    "azureADOnlyAuthentication": true,
                    "principalType": "Group"
                },
                "version": "12.0",
                "minimalTlsVersion": "1.2",
                "publicNetworkAccess": "Enabled",
                "restrictOutboundNetworkAccess": "Enabled"
            },
            "identity": {
                "type": "SystemAssigned"
            },
            "resources": [
                {
                    "type": "connectionPolicies",
                    "name": "Default",
                    "apiVersion": "2014-04-01",
                    "dependsOn": [
                        "[resourceId('Microsoft.Sql/servers', parameters('serverName'))]"
                    ],
                    "properties": {
                        "connectionType": "[parameters('connectionType')]"
                    }
                }
            ]
        }
however i am getting an issue below
Status Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details. (Code: DeploymentFailed)
 - {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "InvalidParameterValue",
        "message": "Invalid value given for parameter AzureADOnlyAuthentication. Specify a valid parameter value."
      }
    ]
  }
} (Code:Conflict)
It working fine till last week, but from last week we are getting an issue above

**Comment by richardsjoberg** [comment]
We are experiencing the same issue as damu9618, it worked a week ago but not anymore

**Comment by atpcln** [comment]
Same problem as @emiacepacIG. If the bicep template contains reference to administrators object, if fails the second time you run it, even if not changes has been made.
Any updates??

**Comment by emanuel-virca** [comment]
Same issue here Status Message: Invalid value given for parameter AzureADOnlyAuthentication. Specify a valid parameter value.

**Comment by twinpiloot** [comment]
I had the same issue and found a workaround. I removed azureADOnlyAuthentication from the administrators property in Microsoft.Sql/servers and added a separate resource for azureADOnlyAuthentication. This works for me.

resource onlyADAuthentication 'Microsoft.Sql/servers/azureADOnlyAuthentications@2023-08-01-preview' = {
  parent: sqlserver
  name: 'Default'
  properties: {
    azureADOnlyAuthentication: true
  }
}

**Comment by jurjenoskam** [comment]
I was trying to reproduce this issue, but to my great surprise I noticed that updating the `login` and `sid` of an Entra ID administrator now seems to work just fine on my server, contrary to my own experiences in the past, everybody's experiences above, and the documentation?! Did something change on the RP end?

Starting without any resource, issuing the following API call works as expected:

`az rest --method put --uri https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/rg-jo-test/providers/Microsoft.Sql/servers/cccjotry123?api-version=2023-08-01 --body @sqlserverbody.json`

... where `sqlserverbody.json` contains (`login` and `sid` are anonymized):

```
{
        "location": "westeurope",
        "properties": {
                "administrators": {
                        "azureADOnlyAuthentication": true,
                        "administratorType": "ActiveDirectory",
                        "login": "User1@example.com",
                        "sid": "11111111-1111-1111-1111-111111111111"
                },
                "publicNetworkAccess": "Disabled",
                "minimalTlsVersion": "1.2"
        }
}
```

After this finishes, there is a server resource called `cccjotry123`  with the settings as specified in the JSON. Re-issuing the same API call with the same body works as expected as well: it's idempotent, so it succeeds without changing anything.

Now the unexpected part: when I change the `login` and `sid` in `sqlserverbody.json` to another account, the same API call does *not* result in an error, and the change *does* happen: the Admin Name and ID shown in the Azure Portal changes from the first account to the second account (that's all I tested - I haven't tried logging in to a database for example). The final status of the async PUT call is:

```
{
  "name": "0f421309-9736-4590-902d-3737a96f331e",
  "startTime": "2025-05-07T08:24:04.6Z",
  "status": "Succeeded"
}
```

I tried changing the `login` and `sid` in a Bicep template as well, and also with API version `2021-11-01`. All with the same result: no errors and the admin is actually changed. Was something changed?

**Comment by PratimDasgupta** [comment]
We have updated our APIs to not have this restriction anymore. This issue should be resolved now.

https://learn.microsoft.com/en-us/azure/azure-sql/database/authentication-azure-ad-only-authentication-create-server?branch=main&branchFallbackFrom=pr-en-us-33923&view=azuresql-mi&tabs=azure-portal#provision-with-microsoft-entra-only-authentication-enabled

You would only need separate API to update the Microsoft Entra Only property.

**Comment by MashaMSFT** [comment]
#please-close

**Comment by alex-frankel** [comment]
Closing as per the update from SQL team.

@PratimDasgupta - can you take a look at the most recent comment to update the property descriptions and other relevant metadata in the Resource Type Swagger spec?

**Comment by JonahBader** [comment]
Are there any plans for fix this so I don't need one template for creating and one template for maintaining? I am using 2024-11-01-preview and it still doesn't work to re-run my initual scripts for Microsoft.Sql/servers.
